"""add debt table

Revision ID: d9f994444fa8
Revises: 9fe529238bd8
Create Date: 2026-01-05 19:24:24.845059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f994444fa8'
down_revision = '9fe529238bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debt_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assigned_agent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debt_case')
    # ### end Alembic commands ###
