"""empty message

Revision ID: 02eaa6216b41
Revises: 36a0208342a8
Create Date: 2026-01-09 16:09:26.178142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02eaa6216b41'
down_revision = '36a0208342a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_escalations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('case_escalations_case_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'debt_cases', ['case_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_escalations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('case_escalations_case_id_fkey'), 'debt_cases', ['case_id'], ['id'])

    # ### end Alembic commands ###
