"""empty message

Revision ID: 0c1d4f04eba0
Revises: d9f994444fa8
Create Date: 2026-01-08 10:51:41.392710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1d4f04eba0'
down_revision = 'd9f994444fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt_cases', schema=None) as batch_op:
        batch_op.drop_column('priority_score')
        batch_op.drop_column('predicted_recovery_probability')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('predicted_recovery_probability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('priority_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
