"""empty message

Revision ID: 36a0208342a8
Revises: d5d83333d756
Create Date: 2026-01-09 16:01:45.762123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a0208342a8'
down_revision = 'd5d83333d756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_model_predictions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ai_model_predictions_case_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'debt_cases', ['case_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('debt_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enterprise_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'organizations', ['enterprise_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt_cases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('enterprise_id')

    with op.batch_alter_table('ai_model_predictions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ai_model_predictions_case_id_fkey'), 'debt_cases', ['case_id'], ['id'])

    # ### end Alembic commands ###
