"""empty message

Revision ID: 507f46e1dbd0
Revises: fe45568a4b09
Create Date: 2026-01-09 04:19:36.481146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '507f46e1dbd0'
down_revision = 'fe45568a4b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('case_activity_logs')
    op.drop_table('role')
    op.drop_table('dca_performance_metrics')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_fs_uniquifier_key'), type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('fs_uniquifier')
        batch_op.drop_column('name')
        batch_op.drop_column('last_login_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fs_uniquifier', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('users_fs_uniquifier_key'), ['fs_uniquifier'], postgresql_nulls_not_distinct=False)

    op.create_table('dca_performance_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dca_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recovery_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_resolution_days', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sla_breach_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_cases_assigned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_cases_closed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('calculated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dca_id'], ['organizations.id'], name=op.f('dca_performance_metrics_dca_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dca_performance_metrics_pkey'))
    )
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('role_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='role_pkey'),
    sa.UniqueConstraint('name', name='role_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('case_activity_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('performed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action_type', postgresql.ENUM('STATUS_UPDATE', 'NOTE', 'CALL', 'EMAIL', 'VISIT', name='activity_type'), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['debt_cases.id'], name=op.f('case_activity_logs_case_id_fkey')),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], name=op.f('case_activity_logs_performed_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('case_activity_logs_pkey'))
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('roles_users_role_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('roles_users_user_id_fkey'))
    )
    # ### end Alembic commands ###
