"""empty message

Revision ID: a702449e859e
Revises: 02eaa6216b41
Create Date: 2026-01-09 16:18:42.002188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a702449e859e'
down_revision = '02eaa6216b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_assignments', schema=None) as batch_op:
        batch_op.alter_column('dca_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('case_assignments_case_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'debt_cases', ['case_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('case_closures', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('case_closures_case_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'debt_cases', ['case_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('case_sla_tracking', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('case_sla_tracking_case_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'debt_cases', ['case_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_organization_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_organization_id_fkey'), 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('case_sla_tracking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('case_sla_tracking_case_id_fkey'), 'debt_cases', ['case_id'], ['id'])

    with op.batch_alter_table('case_closures', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('case_closures_case_id_fkey'), 'debt_cases', ['case_id'], ['id'])

    with op.batch_alter_table('case_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('case_assignments_case_id_fkey'), 'debt_cases', ['case_id'], ['id'])
        batch_op.alter_column('dca_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
