"""empty message

Revision ID: d5d83333d756
Revises: 507f46e1dbd0
Create Date: 2026-01-09 15:53:43.152018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d83333d756'
down_revision = '507f46e1dbd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_model_predictions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ai_model_predictions_case_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'debt_cases', ['case_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('debt_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enterprise_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'organizations', ['enterprise_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt_cases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('enterprise_id')

    with op.batch_alter_table('ai_model_predictions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ai_model_predictions_case_id_fkey'), 'debt_cases', ['case_id'], ['id'])

    # ### end Alembic commands ###
