"""empty message

Revision ID: e6d6fc15d146
Revises: a702449e859e
Create Date: 2026-01-09 16:54:58.728267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6d6fc15d146'
down_revision = 'a702449e859e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_closures', schema=None) as batch_op:
        batch_op.alter_column('closure_reason',
               existing_type=postgresql.ENUM('PAID', 'WRITE_OFF', 'DISPUTE', name='closure_reason'),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_closures', schema=None) as batch_op:
        batch_op.alter_column('closure_reason',
               existing_type=sa.String(length=255),
               type_=postgresql.ENUM('PAID', 'WRITE_OFF', 'DISPUTE', name='closure_reason'),
               existing_nullable=True)

    # ### end Alembic commands ###
